### PR TITLE
Fail if a mock is dropped without having called `.done()` exactly once

### LINKED ISSUE #34: Implement `Drop` for mocks which executes `done()`
When writing tests it's easy to forget a call to `done()` at the end to verify if there are any expectations left. By executing it in drop one can't forget it.

```rust
// will pass if no transaction happens 
#[test]
fn test() {
        let expectations = [
            Transaction::write(0x58, vec![0xab, 0xcd]),
        ];
        let mut mock = I2cMock::new(&expectations);
}
```

### PR DESCRIPTION
**Pull request by dbrgn**
Not calling `.done()` is a potential bug. Print a warning to stderr and fail the test if `done()` is not called exactly once.

I first thought about putting the strict checking behind a feature flag, but it's better to simply release a breaking release (0.10) instead.

Fixes #34.

### CODE REVIEW

File: src/common.rs [hunk 1]
```diff
@@ -87,19 +96,93 @@ where
...
+            use std::io::Write;
+            let mut stderr = std::io::stderr();
+            stderr.write_all(b"\x1b[31m").ok();
+            stderr.write_all(msg.as_bytes()).ok();
+            stderr.write_all(b"\x1b[m\n").ok();
+            stderr.flush().ok();
+
+            // Panic. This probably results in an abort:
+            // https://doc.rust-lang.org/std/ops/trait.Drop.html#panics
+            panic!("{}", msg);
```
Comment (rnestler) [inline src/common.rs:142]: Why should this result in an abort? Only if we *not* check for `!thread::panicking`, right?

File: src/common.rs [hunk 2]
```diff
@@ -4,12 +4,13 @@ use std::{
...
     sync::{Arc, Mutex},
+    thread,
 };
 
 /// Generic mock implementation.
 ///
-/// ⚠️ **Do not use this directly as end user! This is only a building
-/// block for creating mocks.**
+/// ⚠️ **Do not use this directly as end user! This is only a building block
+/// for creating mocks.**
```
Comment (rnestler) [inline src/common.rs:13]: Why is it `pub` if it isn't supposed to be used as and user?

Comment (dbrgn) [reply src/common.rs:13]: Because our mocks are aliases too concrete instances of `GenericMock<T>`, for example `pub type Mock = Generic<Transaction>`.

If we change the visibility to `pub(crate)` and try to compile:

```
error[E0446]: crate-private type `common::Generic<eh0::spi::Transaction>` in public interface
   --> src/eh0/spi.rs:120:1
    |
120 | pub type Mock = Generic<Transaction>;
    | ^^^^^^^^^^^^^ can't leak crate-private type
    |
   ::: src/common.rs:24:1
    |
24  | pub(crate) struct Generic<T: Clone + Debug + PartialEq> {
    | ------------------------------------------------------- `common::Generic<eh0::spi::Transaction>` declared as crate-private
```

File: src/common.rs (hunk 1 above)
Comment (dbrgn) [reply src/common.rs:142]: Yeah, I think you're right.

Comment (dbrgn) [reply src/common.rs:142]: Note updated in https://github.com/dbrgn/embedded-hal-mock/pull/79
